### ISSUE TITLE
Rename classes/file to better express their role

### ISSUE THREAD

**Issue by DocOnDev** [DocOnDev/team_joy#8]
Make sure to update spec file names to match

- CommitMessageHandler to GitCommitMessageHandler
- CommitMessageWriter to GitCommitMessageWriter
- CommitScoreWriter to GitCommitScoreWriter
- PostCommitHandler to GitPostCommitHandler

**Comment by RishiKumarRay** [comment]
I would like to do this

**Comment by DocOnDev** [comment]
@RishiKumarRay - feel free!

**Comment by DocOnDev** [comment]
Make sure to update the file names as well as the class names. There is a naming convention. I am hoping it is obvious, but if it is not, please let me know.

**Comment by RishiKumarRay** [comment]
No problem , you can continue
